package team.inreok.poppyserver.global.error

import org.springframework.http.HttpStatus

enum class ErrorCode(
    val status: HttpStatus,
    val code: String,
    val message: String,
) {
    INVALID_INPUT(HttpStatus.BAD_REQUEST, "COMMON_400", "요청 값이 올바르지 않습니다"),
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "COMMON_500", "서버 내부 오류가 발생했습니다"),
    ROBOT_REGISTRATION_INVALID(HttpStatus.BAD_REQUEST, "ROBOT_REGISTRATION_INVALID", "Robot registration data is invalid"),
    ROBOT_ALREADY_REGISTERED(HttpStatus.CONFLICT, "ROBOT_ALREADY_REGISTERED", "The Robot is already registered"),
    ROBOT_COMPATIBILITY_NOT_VERIFIED(HttpStatus.UNPROCESSABLE_ENTITY, "ROBOT_COMPATIBILITY_NOT_VERIFIED", "Robot compatibility is not verified"),
    ROBOT_FILTER_INVALID(HttpStatus.BAD_REQUEST, "ROBOT_FILTER_INVALID", "The Robot filter is invalid"),
    ROBOT_NOT_FOUND(HttpStatus.NOT_FOUND, "ROBOT_NOT_FOUND", "The Robot was not found"),
    ROBOT_UPDATE_CONFLICT(HttpStatus.CONFLICT, "ROBOT_UPDATE_CONFLICT", "The Robot cannot be changed while it is executing"),
    ROBOT_CAPABILITY_INVALID(HttpStatus.UNPROCESSABLE_ENTITY, "ROBOT_CAPABILITY_INVALID", "The Robot capability is invalid"),
    AGENT_AUTH_INVALID(HttpStatus.UNAUTHORIZED, "AGENT_AUTH_INVALID", "The Agent authentication is invalid"),
    AGENT_PRINCIPAL_MISMATCH(HttpStatus.FORBIDDEN, "AGENT_PRINCIPAL_MISMATCH", "The authenticated Agent does not match the requested Agent"),
    AGENT_REGISTRATION_INVALID(HttpStatus.BAD_REQUEST, "AGENT_REGISTRATION_INVALID", "The Agent registration data is invalid"),
    AGENT_ALREADY_REGISTERED(HttpStatus.CONFLICT, "AGENT_ALREADY_REGISTERED", "The Agent is already registered"),
    AGENT_COMPATIBILITY_INVALID(HttpStatus.UNPROCESSABLE_ENTITY, "AGENT_COMPATIBILITY_INVALID", "The Agent and Robot are incompatible"),
    AGENT_NOT_FOUND(HttpStatus.NOT_FOUND, "AGENT_NOT_FOUND", "The Agent was not found"),
    AGENT_ROBOT_BINDING_MISMATCH(HttpStatus.CONFLICT, "AGENT_ROBOT_BINDING_MISMATCH", "The Agent and Robot binding does not match"),
    HEARTBEAT_PAYLOAD_INVALID(HttpStatus.BAD_REQUEST, "HEARTBEAT_PAYLOAD_INVALID", "The heartbeat payload is invalid"),
    EXECUTION_DELIVERY_INVARIANT_VIOLATED(HttpStatus.INTERNAL_SERVER_ERROR, "EXECUTION_DELIVERY_INVARIANT_VIOLATED", "The Execution delivery assignment is invalid"),
    EXECUTION_NOT_FOUND(HttpStatus.NOT_FOUND, "EXECUTION_NOT_FOUND", "The Execution was not found"),
    EXECUTION_ROBOT_MISMATCH(HttpStatus.CONFLICT, "EXECUTION_ROBOT_MISMATCH", "The Execution is not assigned to the Robot"),
    EXECUTION_CANCELLATION_NOT_ALLOWED(HttpStatus.CONFLICT, "EXECUTION_CANCELLATION_NOT_ALLOWED", "The Execution cannot be cancelled in its current status"),
    EXECUTION_CANCELLATION_INVARIANT_VIOLATED(HttpStatus.INTERNAL_SERVER_ERROR, "EXECUTION_CANCELLATION_INVARIANT_VIOLATED", "The Execution cancellation assignment is invalid"),
    EXECUTION_STATUS_UNSUPPORTED(HttpStatus.BAD_REQUEST, "EXECUTION_STATUS_UNSUPPORTED", "The Execution status is unsupported"),
    EXECUTION_STATUS_TRANSITION_INVALID(HttpStatus.CONFLICT, "EXECUTION_STATUS_TRANSITION_INVALID", "The Execution status transition is invalid"),
    SESSION_NOT_FOUND(HttpStatus.NOT_FOUND, "SESSION_NOT_FOUND", "The Session was not found"),
    SESSION_TOKEN_INVALID(HttpStatus.UNAUTHORIZED, "SESSION_TOKEN_INVALID", "The Session token is invalid"),
    SESSION_EXPIRED(HttpStatus.GONE, "SESSION_EXPIRED", "The Session has expired"),
    EXECUTION_ACCESS_DENIED(HttpStatus.FORBIDDEN, "EXECUTION_ACCESS_DENIED", "The Execution does not belong to the Session"),
    BLOCK_REVISION_NOT_FOUND(HttpStatus.NOT_FOUND, "BLOCK_REVISION_NOT_FOUND", "The Block Revision was not found"),
    SIMULATION_BLOCK_VERSION_INVALID(HttpStatus.BAD_REQUEST, "SIMULATION_BLOCK_VERSION_INVALID", "The simulation block version is invalid"),
    SIMULATION_BLOCK_VERSION_STALE(HttpStatus.CONFLICT, "SIMULATION_BLOCK_VERSION_STALE", "The simulation block version is not current"),
    SIMULATION_PASS_NOT_FOUND(HttpStatus.CONFLICT, "SIMULATION_PASS_NOT_FOUND", "The Simulation Pass was not found"),
    EXECUTION_SESSION_ACTIVE(HttpStatus.CONFLICT, "EXECUTION_SESSION_ACTIVE", "The Session already has an active Execution"),
}
