CREATE TABLE robots (
    id UUID PRIMARY KEY,
    alias TEXT NOT NULL,
    model TEXT NOT NULL,
    edition TEXT NOT NULL,
    firmware_version TEXT,
    sdk_version TEXT,
    agent_id UUID,
    safety_profile_id UUID,
    is_external BOOLEAN NOT NULL,
    connection_status TEXT NOT NULL,
    operational_status TEXT NOT NULL,
    current_execution_id UUID,
    last_heartbeat_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX uq_robots_agent_id
    ON robots (agent_id)
    WHERE agent_id IS NOT NULL;

CREATE TABLE robot_capabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    robot_id UUID NOT NULL REFERENCES robots (id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    support_status TEXT NOT NULL,
    CONSTRAINT uq_robot_capability_code UNIQUE (robot_id, code)
);
